### ISSUE TITLE
Main Socket Handler Error

### ISSUE THREAD

**Issue by DOWRIGHTTV** [DOWRIGHTTV/DNS-over-TLS-Relay#2]
Traceback (most recent call last):
  File "dns_tls_relay.py", line 59, in Main
    packet.Parse()
  File "dns_tls_relay.py", line 277, in Parse
    self.QName()
  File "dns_tls_relay.py", line 301, in QName
    length = qname[0] + 1
IndexError: tuple index out of range
MAIN: tuple index out of range

**Comment by DOWRIGHTTV** [comment]
this has been resolved.
